[bot]
plugin_dirs = ["plugins"]
adapters = ["iamai.adapter.cqhttp", "iamai.adapter.apscheduler"]

[bot.log]
level = "INFO"
verbose_exception = true

[adapter.cqhttp]
adapter_type = "ws-reverse"
host = "0.0.0.0"
port = 3001
url = "/cqhttp/ws"

[adapter.apscheduler]
scheduler_config = { "apscheduler.timezone" = "Asia/Shanghai" }